### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [fideviva/Instagram-post#1]
# Revisión - Aprobado
- [x] Estilo de código y limpieza
# Feedback
- ¡Buen trabajo. Felicidades @fideviva  !
## Estilo de código y limpieza
- ¡Muy bien hecho!
## Mejores prácticas/comentarios
- En el archivo index.html, debes cerrar la etiqueta `<head>` correctamente agregando `</head>`
- Tendrías que ajustar el texto inferior para dejar un poco de margen a ambos lados 
![Captura de pantalla de 2024-03-07 09-19-32](https://github.com/fideviva/Instagram-post/assets/139759297/902c3dbc-9ad8-4510-b603-dd0bf00a082a)
- Recuerda que a la hora de crear un nuevo repositorio lo tienes que hacer seleccionando a la academia como owner 
![Captura de pantalla de 2024-03-07 09-17-25](https://github.com/fideviva/Instagram-post/assets/139759297/53bb1e37-122a-4f65-a42e-f5b995dbb1f5)

**Comment by fideviva** [comment]
Hola, Eduardo. Ya resolví lo del Owner creo que ahora esta bien, lo deberías de ver  en los otros proyectos que entregué. Corregiré esos errores y actualizaré el proyecto. Muchas gracias!

**Comment by EduardoHernandezGuzman** [comment]
Buen trabajo!!!
